### ISSUE TITLE
Restoring Pdf

### ISSUE THREAD

**Issue by charlesroddie** [fsprojects/fsharp-cheatsheet#17]
Pdf output was removed in https://github.com/fsprojects/fsharp-cheatsheet/pull/14

I assume that was done because the build process was difficult (going via latex)? But the overall effect is very radical, with users viewing this in a browser vs previously on paper or a reader app.

Pdf should be restorable. For example pandoc can go from .md to .pdf. https://github.com/pandoc/pandoc-action-example

**Comment by bartelink** [comment]
From my perspective it would obviously be nice, but something that's automated and Just Works is key.
Do you have the capacity/interest to take a stab at it?
If there's anything that can be done to facilitate progressing it, I'm happy to do it

**Comment by SpiralOSS** [comment]
I had it in the plan to create another GitHub action that creates a PDF from the HTML or Markup, but was focused on the sheet itself. I'll take a look this weekend.

**Comment by SpiralOSS** [comment]
Tried two actions, but I get errors. I'm missing something about actions. Will have to pick this up a little later.

**Comment by SpiralOSS** [comment]
> Pdf should be restorable. For example pandoc can go from .md to .pdf. https://github.com/pandoc/pandoc-action-example

I somehow missed this comment, will try this tomorrow.
