### ISSUE TITLE
explain use of '

### ISSUE THREAD

**Issue by daveyostcom** [fsprojects/fsharp-cheatsheet#9]
The text should explain the use of the single quote here.
```
let squareNegateThenPrint' = 
    square >> negate >> print
```
and here
```
collections implementing IEnumerable<'T>
```
and while you're at it, other related topics, such as ```triple backquotes```.

**Comment by SpiralOSS** [comment]
```F#
let squareNegateThenPrint' = 
    square >> negate >> print
```

Prime tick is in the latest PR, which will be merged shortly.

The others come to come soon.

**Comment by daveyostcom** [comment]
Ok
